name:  Product Requirements
description: Product Requirements 
title: "[Prod-Req]"
labels: ["product requirements"]
projects: ["product requirements"]
assignees:
- bnieuwborg
- ajcraig
body:
  - type: textarea
    id: Requirements
    attributes:
      label: Requirements Description
      description: 
      placeholder: Requirement features and details (Required)
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: deliverables-impacted
    attributes:
      label: deliverables impacted
      description: 
      placeholder: PMG deliverables impacted via the requirement(not required)
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: Requirements Description
    attributes:
      label: Milestone
      description: 
      placeholder: Desired milestone/snap-shot PMG wants to include (Not Required)
      value: "Add details"
    validations:
      required: true
  - type: textarea
    id: Requirements Description
    attributes:
      label: Workflow
      description: 
      placeholder: Associated user workflow (Required)
      value: "Add details"
    validations:
      required: true
  - type: dropdown
    id: Focus-Groups
    attributes:
      label: Requirement dependency with other Focus Groups
      multiple: true
      options:
        - No Dependency
        - App-package-definition
        - App-Observability
        - Device-Requirements
        - Workload Orchestration Agent Interfaces
        - End-to-end prototypes
        - Security

