name:  Product Requirements
description: Product Requirements 
title: "[Prod-Req]"
labels: ["PM - Requirement in Draft"]
projects: ["product management"]
assignees:
- abbottjd
- bnieuwborg
body:
  - type: textarea
    id: Requirements
    attributes:
      label: Requirements Description (Required)
      description: 
      placeholder: Requirement features and details
      value: "Add details - Requirement features and details"
    validations:
      required: true
  - type: textarea
    id: Requirements-Description
    attributes:
      label: Milestone (Not Required)
      description: 
      placeholder: Desired milestone/snap-shot PMG wants to include
      value: "Add details - Desired milestone/snap-shot PMG wants to include."
    validations:
      required: true
  - type: textarea
    id: Non-Functional-Requirements
    attributes:
      label: Non-Functional Requirements (not required)
      description: 
      placeholder: Associated user workflow
      value: "Add details-Non-Functional-Requirements"
    validations:
      required: true
  - type: textarea
    id: Related-User-Journey
    attributes:
      label: Related User Journey
      description: 
      placeholder: Associated User Journey
      value: "Add related user journey name"
    validations:
      required: true
  - type: textarea
    id: User-Journey-Step-Number
    attributes:
      label: User Journey Step number
      description: 
      placeholder: User Journey Step Number
      value: "Add User Journey Step Number"
    validations:
      required: true     
  - type: dropdown
    id: Focus-Groups
    attributes:
      label: Requirement dependency with other Focus Groups
      multiple: true
      options:
        - No Dependency
        - App-package-definition
        - App-Observability
        - Device-Requirements
        - Workload Orchestration Agent Interfaces
        - End-to-end prototypes
        - Security

