name:  Product Requirements
description: Product Requirements 
title: "[Prod-Req]"
labels: ["product requirements"]
projects: ["product requirements"]
assignees:
- bnieuwborg
- ajcraig
body:
  - type: textarea
    id: Requirements
    attributes:
      label: Requirements Description (Required)
      description: 
      placeholder: Requirement features and details
      value: "Add details-Requirement features and details"
    validations:
      required: true
  - type: textarea
    id: Deliverables-Impacted
    attributes:
      label: deliverables impacted (not required)
      description: 
      placeholder: PMG deliverables impacted via the requirement
      value: "Add details-PMG deliverables impacted via the requirement."
    validations:
      required: true
  - type: textarea
    id: Requirements-Description
    attributes:
      label: Milestone (Not Required)
      description: 
      placeholder: Desired milestone/snap-shot PMG wants to include
      value: "Add details-Desired milestone/snap-shot PMG wants to include."
    validations:
      required: true
  - type: textarea
    id: Workflow
    attributes:
      label: Workflow (Required)
      description: 
      placeholder: Associated user workflow
      value: "Add details-Associated user workflow"
    validations:
      required: true
  - type: textarea
    id: Non-Functional-Requirements
    attributes:
      label: Non-Functional Requirements(not required)
      description: 
      placeholder: Associated user workflow
      value: "Add details-Non-Functional-Requirements"
    validations:
      required: true
  - type: dropdown
    id: Focus-Groups
    attributes:
      label: Requirement dependency with other Focus Groups
      multiple: true
      options:
        - No Dependency
        - App-package-definition
        - App-Observability
        - Device-Requirements
        - Workload Orchestration Agent Interfaces
        - End-to-end prototypes
        - Security

